package modelo;
// Generated 19 ene 2026, 11:56:49 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import com.google.gson.annotations.Expose;

/**
 * Ciclos generated by hbm2java
 */
public class Ciclos implements java.io.Serializable {
	@Expose
	private Integer id;
	@Expose
	private String nombre;
	 
    @OneToMany(mappedBy = "ciclos")
	private Set moduloses = new HashSet(0);
	 
    @OneToMany(mappedBy = "ciclos")
	private Set matriculacioneses = new HashSet(0);

	public Ciclos() {
	}

	public Ciclos(String nombre) {
		this.nombre = nombre;
	}

	public Ciclos(String nombre, Set moduloses, Set matriculacioneses) {
		this.nombre = nombre;
		this.moduloses = moduloses;
		this.matriculacioneses = matriculacioneses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getModuloses() {
		return this.moduloses;
	}

	public void setModuloses(Set moduloses) {
		this.moduloses = moduloses;
	}

	public Set getMatriculacioneses() {
		return this.matriculacioneses;
	}

	public void setMatriculacioneses(Set matriculacioneses) {
		this.matriculacioneses = matriculacioneses;
	}

}
